blog/urls.py
"""Defines URL patterns for my website"""

from django.conf.urls import url

from . import views

urlpatterns = [
	#Home page
	url(r'^$', views.index, name='index'),

	#Show all Topics
	url(r'^topics/$', views.topics, name = 'topics'),

	#Detail page for a single topic
	url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name = 'topic'),

	url(r'^about/', views.about, name = 'about'),

	url(r'^projects/$', views.projects, name = 'projects'),

	url(r'^projects/(?P<project_id>\d+)/$', views.project, name = 'project'),
	]

mywebsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls', namespace = 'blog')),
]

blog/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
	"""A topic that I am writing about"""
	text = models.CharField(max_length = 200)
	date_added = models.DateTimeField(auto_now_add = True)

	def __str__(self):
		"""Return a string representation of the model."""
		return self.text
		
class Entry(models.Model):
	"""A post in a section of my blog"""
	topic = models.ForeignKey(Topic)
	title = models.TextField(default="Title")
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add = True)

	class Meta:
		verbose_name_plural = 'entries'

	def __str__(self):
		"""Return a string representation of the model. Make it limited to 50 characters"""
		if len(self.text) > 50:
			return self.text[:50] + "..."
		else:
			return self.text

class Project(models.Model):
	"""A project of mine"""
	title = models.TextField(default="Title")
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add = True)

	def __str__(self):
		"""Returns a string representation of the project"""
		return self.title
		
class Picture(models.Model):
	"""Pictures for a Project"""
	project = models.ForeignKey(Project)
	url = models.TextField()
	title = models.TextField()

	def __str__(self):
		"""Returns string representation of the Picture"""
		return self.title
		

blog/views.py
from django.shortcuts import render

from .models import Topic, Project
# Create your views here.
def index(request):
	"""The home page for my website"""
	return render(request, 'blog/index.html')

def topics(request):
	"""Show all topics"""
	topics = Topic.objects.order_by('date_added')
	context = {'topics': topics}
	return render(request, 'blog/topics.html', context)

def topic(request, topic_id):
	"""Show a single topic and all its entries"""
	topic = Topic.objects.get(id = topic_id)
	entries = topic.entry_set.order_by('-date_added')
	context = {'topic': topic, 'entries': entries}
	return render(request, 'blog/topic.html', context)

def about(request):
	"""The about page for my website"""
	return render(request, 'blog/about.html')

def projects(request):
	"""The Projects page for my website"""
	projects = Project.objects.order_by('-date_added')
	context = {'projects': projects}
	return render(request, 'blog/projects.html', context)

def project(request, project_id):
	"""A more in depth view of the project with pictures"""
	project = Project.objects.get(id = project_id)
	pictures = project.picture_set.order_by('id')
	context = {'pictures': pictures, 'project': project}
	return render(request, 'blog/project.html', context)

blog/templates/blog/base.html
{% load bootstrap3 %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<title>David Thurman</title>

		{% bootstrap_css %}
		{% bootstrap_javascript %}
		<link rel="stylesheet" href="{% static 'css/index.css' %}">
	</head>

	<body>
		<!-- Static Navbar -->

		<nav class="navbar navbar-default navbar-static-top">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
					</button>
					<a class="navbar-brand" href="{% url 'blog:index' %}" style="margin-top:13px;">David Thurman</a>
				</div>

				<div id="navbar" class="navbar-collapse collapse">
					<ul class="nav navbar-nav">
<!-- 						<li><a href="{% url 'blog:topics' %}">Blog</a></li>
 -->						<li><a href="{% url 'blog:projects' %}">Projects</a></li>
						<li><a href="https://github.com/davidthurman/"><img src="{% static "images/githublogo.png" %}" /> Github</a></li>
						<li><a href="https://www.linkedin.com/in/david-thurman-643124113"><img src="{% static "images/linkedinlogo.png" %}"> LinkedIn</a></li>
					</ul>

				</div><!--/.nav-collapse -->
			</div>
		</nav>

		<div class="container">
			<div class="page-header">
				{% block header %}{% endblock %}
			</div>
			<div>
				{% block content %}{% endblock content %}
			</div>
		</div><!-- /container -->
	</body>
</html>

blog/templates/blog/baseWithoutHeader.html
{% load bootstrap3 %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<title>David Thurman</title>

		{% bootstrap_css %}
		{% bootstrap_javascript %}
		<link rel="stylesheet" href="{% static 'css/index.css' %}">
	</head>

	<body>
		<!-- Static Navbar -->
		<div class="bg"/></div>
		<nav class="navbar navbar-default navbar-static-top">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
					</button>
					<a class="navbar-brand" href="{% url 'blog:index' %}" style="margin-top:13px;">David Thurman</a>
				</div>

				<div id="navbar" class="navbar-collapse collapse">
					<ul class="nav navbar-nav">
<!-- 						<li><a href="{% url 'blog:topics' %}">Blog</a></li>
 -->						<li><a href="{% url 'blog:projects' %}">Projects</a></li>
						<li><a href="https://github.com/davidthurman/"><img src="{% static "images/githublogo.png" %}" /> Github</a></li>
						<li><a href="https://www.linkedin.com/in/david-thurman-643124113"><img src="{% static "images/linkedinlogo.png" %}"> LinkedIn</a></li>
					</ul>

				</div><!--/.nav-collapse -->
			</div>
		</nav>

		<div class="container">
			<div>
				{% block content %}{% endblock content %}
			</div>
		</div><!-- /container -->
	</body>
</html>

blog/templates/blog/index.html
{% extends "blog/baseWithoutHeader.html" %}
{% load staticfiles %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% block content %}

<div style="display:flex;margin:0 auto;">

	<div class="contentWrapper" id="myPicWrapper">
		<img src="{% static "images/personalPic.jpg" %}" style="margin-top:20px;" class="personalPic"/>
		<p id="jobTitle">Application Developer</p>
		<p id="name">David Thurman</p>
	</div>
	<div class="contentWrapper" id="workExperience">
		<h3 style="text-align: center">Work Experience</h3>
		<p style="font-size: 18px;">DVIDS</p>
		<p style="font-size: 12px;">&nbsp;&nbsp;4/16 - Present</p>
		<p style="margin-left: 20px;margin-bottom:30px;">I work as an Application Developer contracted by the Military to develop various kinds of applications and maintain our current devices' apps. Some of the platforms I work on regularly include iOS, tvOS, Roku, Amazon Fire, and Android TV. I also work web development on dvidshub.net, using PHP and JavaScript, and defensetv.com, using AngularJS. I also work on a wide variety of different projects including a C# application for DVIDS that utilizes the DVIDS API and a built in media player, a Python GUI application that compresses videos using FFmpeg and x265 with up to 900% reduction in size and slight quality differences, and working on security fixes for a web based video conference application in Java.</p>

		<p style="font-size: 18px;">DevelAppMe</p>
		<p style="font-size: 12px;">&nbsp;&nbsp;9/15 - 12/15</p>
		<p style="margin-left: 20px;">Certiﬁed in completing the Professional Development DevelAppMe Academy three month program in which I created many mobile apps from start to ﬁnish along with constant group collaboration and experience in using Scrum. </p>
		
	</div>
	
</div>

<div style="display:flex;margin: auto; ">
	<div class="contentWrapper" id="specialtiesWrapper">
		<h3 style="text-align: center">Specialties</h3>
		<div style="text-align: center">
			<div class="skillsList" style="float:left">
				<ul class="specialties">
					<li style="margin-top: 40px">iOS Development</li>
					<li style="margin-top: 50px">Python Applications</li>
					<li style="margin-top: 50px">.NET (UWP)</li>
					<li style="margin-top: 50px">Video Compression</li>
				</ul>
			</div>
		</div>
	</div>

	<div class="contentWrapper" id="languageWrapper">
		<h3 class="contentTitle">Languages</h3>
		<p style="text-align: center"><img src="{% static "images/pawn.png" %}" /> = Proficiency</p>
		<div class="skillsList">
      		<ul>
	      		<li>Swift&nbsp;&nbsp;&nbsp; <img src="{% static "images/pawn.png" %}"/><img src="{% static "images/pawn.png" %}"/><img src="{% static "images/pawn.png" %}"/><img src="{% static "images/pawn.png" %}"/><img src="{% static "images/pawn.png" %}"/></li>
	      		<li>Python <img src="{% static "images/pawn.png" %}"/><img src="{% static "images/pawn.png" %}"/><img src="{% static "images/pawn.png" %}"/><img src="{% static "images/pawn.png" %}"/><img src="{% static "images/pawn.png" %}"/></li>
	      		<li>C#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="{% static "images/pawn.png" %}"/><img src="{% static "images/pawn.png" %}"/><img src="{% static "images/pawn.png" %}"/><img src="{% static "images/pawn.png" %}"/></li>
	      		<li>Java&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="{% static "images/pawn.png" %}"/><img src="{% static "images/pawn.png" %}"/><img src="{% static "images/pawn.png" %}"/></li>
	      	</ul>
      	</div>
      	<div class="skillsList">
      		<ul>
      			<li>Android&nbsp;<img src="{% static "images/pawn.png" %}"/><img src="{% static "images/pawn.png" %}"/><img src="{% static "images/pawn.png" %}"/></li>
      			<li>SQL&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="{% static "images/pawn.png" %}"/><img src="{% static "images/pawn.png" %}"/><img src="{% static "images/pawn.png" %}"/></li>
      			<li>PHP&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="{% static "images/pawn.png" %}"/><img src="{% static "images/pawn.png" %}"/><img src="{% static "images/pawn.png" %}"/></li>
      			<li>HTML&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="{% static "images/pawn.png" %}"/><img src="{% static "images/pawn.png" %}"/><img src="{% static "images/pawn.png" %}"/></li>      			
      		</ul>	
	    </div>
	    <div class="skillsList">
      		<ul>
      			<li>CSS&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="{% static "images/pawn.png" %}"/><img src="{% static "images/pawn.png" %}"/></li>
      			<li>C++&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="{% static "images/pawn.png" %}"/><img src="{% static "images/pawn.png" %}"/></li>
      			<li>Javascript&nbsp;&nbsp;&nbsp;<img src="{% static "images/pawn.png" %}"/></li>
      			<li>Objective-C&nbsp;<img src="{% static "images/pawn.png" %}"/></li>
      		</ul>	
	    </div>
	</div>
	
	
</div>


<div style="display:flex;margin: auto; ">

	<div class="contentWrapper" id="specialtiesWrapper">
		<h3 style="text-align: center">Contact Me</h3>
		<div style="">
			<div class="skillsList" style="float:left">
				<p class="contactTitle">Email</p>
				<p class="contactInfo">davidthurmanwork@gmail.com</p>
				<p class="contactTitle">Phone</p>
				<p class="contactInfo">678-699-4527</p>
			</div>
		</div>
	</div>

	<div class="contentWrapper" id="frameworksWrapper">
		<h3 class="contentTitle">Frameworks, Source Control, Tools, Misc.</h3>
		<div style="text-align: left">
			<div class="skillsList" >
				<ul class="frameworks">
					<li>Django</li>
					<li>Laravel</li>
					<li>Git</li>
					<li>Github</li>
					
				</ul>
			</div>
			<div class="skillsList" >
				<ul class="frameworks">
					<li>Mercurial</li>
					<li>Bitbucket</li>
					<li>Project Management</li>
					<li>Agile Methodologies</li>
					
				</ul>
			</div>
			<div class="skillsList">
				<ul class="frameworks">
					<li>Scrum</li>
					<li>Xcode</li>
					<li>Visual Studio</li>
					<li>Android Studio</li>
				</ul>
			</div>
		</div>
	</div>
	
</div>

{% endblock content %}

blog/templates/blog/project.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block header %}
	<link rel="stylesheet" href="{% static 'css/index.css' %}">
	<h2>{{ project }}</h2>
{% endblock header %}

{% block content %}
	<ul>
		
			<div class="panel panel-default">
				<div class="panel-heading">
					
					<h3>
						{{ project.text }}
						<!--{{ entry.date_added|date:'M d, Y H:i' }}-->
					</h3>
					
				</div>
				
				<div class="panel-body">
					{% for x in pictures %}
						<img class="projectPic" src="{% static x.url %}"/>
						<h3 class="projectTitle">{{ x.title }}</h3>
					{% empty %}

					{% endfor %}
				</div>
				
			</div>
		
	</ul>

{% endblock content %}

blog/templates/blog/projects.html
{% extends "blog/base.html" %}
{% load staticfiles %}

{% block header %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
	<h1>Projects</h1>
{% endblock header %}

{% block content %}

	<ul>
		{% for project in projects %}
			<li>
				<h3>
					<a href="{% url 'blog:project' project.id %}">{{ project }}</a>
				</h3>
			</li>
		{% empty %}
			<li>No projects have been added yet.</li>
		{% endfor %}
	</ul>
{% endblock content %}

blog/templates/blog/topic.html
{% extends 'blog/base.html' %}

{% block header %}
	<h2>{{ topic }}</h2>
{% endblock header %}

{% block content %}

	<ul>
		{% for entry in entries %}
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3>
						{{ entry.title }}
						<!--{{ entry.date_added|date:'M d, Y H:i' }}-->
					</h3>
				</div>
				<div class="panel-body">
					{{ entry.text|linebreaks }}
				</div>
			</div>
		{% empty %}
			There are no entries for this topic yet.
		{% endfor %}
	</ul>

{% endblock content %}

blog/templates/blog/topics.html
{% extends "blog/base.html" %}

{% block header %}
	<h1>Topics</h1>
{% endblock header %}

{% block content %}

	<ul>
		{% for topic in topics %}
			<li>
				<h3>
					<a href="{% url 'blog:topic' topic.id %}">{{ topic }}</a>
				</h3>
			</li>
		{% empty %}
			<li>No topics have been added yet.</li>
		{% endfor %}
	</ul>
{% endblock content %}

blog/templates/projects/projectslist.html
{% extends 'blog/base.html' %}

{% block header %}
	<h2>{{ topic }}</h2>
{% endblock header %}

{% block content %}

	<ul>
		{% for entry in entries %}
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3>
						{{ entry.title }}
						<!--{{ entry.date_added|date:'M d, Y H:i' }}-->
					</h3>
				</div>
				<div class="panel-body">
					{{ entry.text|linebreaks }}
				</div>
			</div>
		{% empty %}
			There are no entries for this topic yet.
		{% endfor %}
	</ul>

{% endblock content %}